"""initial_schema

Revision ID: 1ac0710e0c5c
Revises: 
Create Date: 2026-09-04 09:20:57.499493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac0710e0c5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('liquidity', sa.String(length=50), nullable=True),
    sa.Column('holding_period', sa.String(length=100), nullable=True),
    sa.Column('interest_or_coupon', sa.String(length=100), nullable=True),
    sa.Column('fees', sa.String(length=255), nullable=True),
    sa.Column('tax_notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('min_investment', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suitable_for', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_products_id'), 'investment_products', ['id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('normalized_category', sa.String(length=50), nullable=True),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_merchant_code'), 'merchants', ['merchant_code'], unique=True)
    op.create_table('payment_provider_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('provider_event_id', sa.String(length=150), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_provider_events_id'), 'payment_provider_events', ['id'], unique=False)
    op.create_index(op.f('ix_payment_provider_events_provider_event_id'), 'payment_provider_events', ['provider_event_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('platform_tenure_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('income_frequency', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('category_saving_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('base_percentage', sa.Float(), nullable=False),
    sa.Column('min_percentage', sa.Float(), nullable=True),
    sa.Column('max_percentage', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_index(op.f('ix_category_saving_policies_id'), 'category_saving_policies', ['id'], unique=False)
    op.create_table('coach_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('coach_response', sa.Text(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('response_source', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_conversations_created_at'), 'coach_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_conversations_id'), 'coach_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_coach_conversations_user_id'), 'coach_conversations', ['user_id'], unique=False)
    op.create_table('credit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('recommended_amount', sa.Float(), nullable=True),
    sa.Column('recommendation_status', sa.String(length=50), nullable=True),
    sa.Column('guardrail_status', sa.String(length=50), nullable=True),
    sa.Column('guardrail_reason_codes', sa.JSON(), nullable=True),
    sa.Column('guardrail_message', sa.Text(), nullable=True),
    sa.Column('distress_level_at_request', sa.String(length=20), nullable=True),
    sa.Column('resilience_score_at_request', sa.Float(), nullable=True),
    sa.Column('partner_offer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_offer_id'], ['partner_credit_offers.id'], name='fk_credit_requests_partner_offer_id', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_requests_created_at'), 'credit_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_requests_id'), 'credit_requests', ['id'], unique=False)
    op.create_index(op.f('ix_credit_requests_user_id'), 'credit_requests', ['user_id'], unique=False)
    op.create_table('distress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('distress_score', sa.Float(), nullable=False),
    sa.Column('distress_level', sa.String(length=20), nullable=False),
    sa.Column('income_decline_pct', sa.Float(), nullable=True),
    sa.Column('expense_ratio', sa.Float(), nullable=True),
    sa.Column('safety_depletion_pct', sa.Float(), nullable=True),
    sa.Column('credit_pressure', sa.Float(), nullable=True),
    sa.Column('resilience_score', sa.Float(), nullable=True),
    sa.Column('consecutive_low_periods', sa.Integer(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(length=100), nullable=True),
    sa.Column('is_sustained', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distress_events_evaluated_at'), 'distress_events', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_distress_events_id'), 'distress_events', ['id'], unique=False)
    op.create_index(op.f('ix_distress_events_user_id'), 'distress_events', ['user_id'], unique=False)
    op.create_table('expense_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('is_large_expense', sa.Boolean(), nullable=True),
    sa.Column('savings_added', sa.Float(), nullable=True),
    sa.Column('save_consent', sa.Boolean(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_transactions_id'), 'expense_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_expense_transactions_transaction_date'), 'expense_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_expense_transactions_user_id'), 'expense_transactions', ['user_id'], unique=False)
    op.create_table('financial_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('historical_avg_income', sa.Float(), nullable=True),
    sa.Column('recent_income', sa.Float(), nullable=True),
    sa.Column('income_trend', sa.String(length=20), nullable=True),
    sa.Column('income_decline_pct', sa.Float(), nullable=True),
    sa.Column('income_volatility', sa.Float(), nullable=True),
    sa.Column('income_volatility_level', sa.String(length=20), nullable=True),
    sa.Column('consecutive_low_periods', sa.Integer(), nullable=True),
    sa.Column('monthly_expenses', sa.Float(), nullable=True),
    sa.Column('weekly_expenses', sa.Float(), nullable=True),
    sa.Column('essential_expenses', sa.Float(), nullable=True),
    sa.Column('non_essential_expenses', sa.Float(), nullable=True),
    sa.Column('expense_to_income_ratio', sa.Float(), nullable=True),
    sa.Column('resilience_score', sa.Float(), nullable=True),
    sa.Column('resilience_label', sa.String(length=30), nullable=True),
    sa.Column('distress_score', sa.Float(), nullable=True),
    sa.Column('distress_level', sa.String(length=20), nullable=True),
    sa.Column('distress_signals', sa.JSON(), nullable=True),
    sa.Column('credit_pressure', sa.Float(), nullable=True),
    sa.Column('platform_tenure_months', sa.Integer(), nullable=True),
    sa.Column('safety_surplus', sa.Float(), nullable=True),
    sa.Column('investment_ready', sa.Boolean(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_financial_profiles_id'), 'financial_profiles', ['id'], unique=False)
    op.create_table('financial_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resilience_score', sa.Float(), nullable=False),
    sa.Column('distress_score', sa.Float(), nullable=False),
    sa.Column('distress_level', sa.String(length=20), nullable=False),
    sa.Column('income_snapshot', sa.Float(), nullable=True),
    sa.Column('expense_snapshot', sa.Float(), nullable=True),
    sa.Column('safety_balance_snapshot', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_score_history_computed_at'), 'financial_score_history', ['computed_at'], unique=False)
    op.create_index(op.f('ix_financial_score_history_id'), 'financial_score_history', ['id'], unique=False)
    op.create_index(op.f('ix_financial_score_history_user_id'), 'financial_score_history', ['user_id'], unique=False)
    op.create_table('income_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('income_type', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_transactions_id'), 'income_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_income_transactions_transaction_date'), 'income_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_income_transactions_user_id'), 'income_transactions', ['user_id'], unique=False)
    op.create_table('investment_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('safety_surplus_at_suggestion', sa.Float(), nullable=True),
    sa.Column('distress_level_at_suggestion', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['investment_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_suggestions_created_at'), 'investment_suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_investment_suggestions_id'), 'investment_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_investment_suggestions_user_id'), 'investment_suggestions', ['user_id'], unique=False)
    op.create_table('linked_payment_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_mask', sa.String(length=20), nullable=True),
    sa.Column('account_holder_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_payment_accounts_id'), 'linked_payment_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_linked_payment_accounts_user_id'), 'linked_payment_accounts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('merchant_upi_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('save_consent', sa.Boolean(), nullable=True),
    sa.Column('suggested_percentage', sa.Float(), nullable=True),
    sa.Column('suggested_save_amount', sa.Float(), nullable=True),
    sa.Column('actual_save_amount', sa.Float(), nullable=True),
    sa.Column('savings_credited', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=150), nullable=True),
    sa.Column('idempotency_key', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_idempotency_key'), 'payment_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_transactions_merchant_id'), 'payment_transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_provider_transaction_id'), 'payment_transactions', ['provider_transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('qr_payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_payment_sessions_id'), 'qr_payment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_qr_payment_sessions_user_id'), 'qr_payment_sessions', ['user_id'], unique=False)
    op.create_table('savings_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('safety_target', sa.Float(), nullable=True),
    sa.Column('save_at_pay_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_save_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_savings_preferences_id'), 'savings_preferences', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('investment_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.String(length=50), nullable=True),
    sa.Column('consent_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['investment_products.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['investment_suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_consents_id'), 'investment_consents', ['id'], unique=False)
    op.create_index(op.f('ix_investment_consents_user_id'), 'investment_consents', ['user_id'], unique=False)
    op.create_table('partner_credit_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_request_id', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('partner_reference', sa.String(length=100), nullable=True),
    sa.Column('offered_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('emi_amount', sa.Float(), nullable=True),
    sa.Column('processing_fee', sa.Float(), nullable=True),
    sa.Column('eligibility_status', sa.String(length=50), nullable=True),
    sa.Column('offer_status', sa.String(length=50), nullable=True),
    sa.Column('offer_terms', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credit_request_id'], ['credit_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_credit_offers_id'), 'partner_credit_offers', ['id'], unique=False)
    op.create_index(op.f('ix_partner_credit_offers_user_id'), 'partner_credit_offers', ['user_id'], unique=False)
    op.create_table('savings_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source_expense_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('category_context', sa.String(length=100), nullable=True),
    sa.Column('save_percentage_applied', sa.Float(), nullable=True),
    sa.Column('balance_before', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_expense_id'], ['expense_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_transactions_created_at'), 'savings_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_savings_transactions_id'), 'savings_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_savings_transactions_user_id'), 'savings_transactions', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('save_consent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('investment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('partner_order_id', sa.String(length=100), nullable=True),
    sa.Column('partner_name', sa.String(length=100), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('partner_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['investment_consents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['investment_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_orders_id'), 'investment_orders', ['id'], unique=False)
    op.create_index(op.f('ix_investment_orders_user_id'), 'investment_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_orders_user_id'), table_name='investment_orders')
    op.drop_index(op.f('ix_investment_orders_id'), table_name='investment_orders')
    op.drop_table('investment_orders')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_savings_transactions_user_id'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_id'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_created_at'), table_name='savings_transactions')
    op.drop_table('savings_transactions')
    op.drop_index(op.f('ix_partner_credit_offers_user_id'), table_name='partner_credit_offers')
    op.drop_index(op.f('ix_partner_credit_offers_id'), table_name='partner_credit_offers')
    op.drop_table('partner_credit_offers')
    op.drop_index(op.f('ix_investment_consents_user_id'), table_name='investment_consents')
    op.drop_index(op.f('ix_investment_consents_id'), table_name='investment_consents')
    op.drop_table('investment_consents')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_savings_preferences_id'), table_name='savings_preferences')
    op.drop_table('savings_preferences')
    op.drop_index(op.f('ix_qr_payment_sessions_user_id'), table_name='qr_payment_sessions')
    op.drop_index(op.f('ix_qr_payment_sessions_id'), table_name='qr_payment_sessions')
    op.drop_table('qr_payment_sessions')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_provider_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_merchant_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_idempotency_key'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_linked_payment_accounts_user_id'), table_name='linked_payment_accounts')
    op.drop_index(op.f('ix_linked_payment_accounts_id'), table_name='linked_payment_accounts')
    op.drop_table('linked_payment_accounts')
    op.drop_index(op.f('ix_investment_suggestions_user_id'), table_name='investment_suggestions')
    op.drop_index(op.f('ix_investment_suggestions_id'), table_name='investment_suggestions')
    op.drop_index(op.f('ix_investment_suggestions_created_at'), table_name='investment_suggestions')
    op.drop_table('investment_suggestions')
    op.drop_index(op.f('ix_income_transactions_user_id'), table_name='income_transactions')
    op.drop_index(op.f('ix_income_transactions_transaction_date'), table_name='income_transactions')
    op.drop_index(op.f('ix_income_transactions_id'), table_name='income_transactions')
    op.drop_table('income_transactions')
    op.drop_index(op.f('ix_financial_score_history_user_id'), table_name='financial_score_history')
    op.drop_index(op.f('ix_financial_score_history_id'), table_name='financial_score_history')
    op.drop_index(op.f('ix_financial_score_history_computed_at'), table_name='financial_score_history')
    op.drop_table('financial_score_history')
    op.drop_index(op.f('ix_financial_profiles_id'), table_name='financial_profiles')
    op.drop_table('financial_profiles')
    op.drop_index(op.f('ix_expense_transactions_user_id'), table_name='expense_transactions')
    op.drop_index(op.f('ix_expense_transactions_transaction_date'), table_name='expense_transactions')
    op.drop_index(op.f('ix_expense_transactions_id'), table_name='expense_transactions')
    op.drop_table('expense_transactions')
    op.drop_index(op.f('ix_distress_events_user_id'), table_name='distress_events')
    op.drop_index(op.f('ix_distress_events_id'), table_name='distress_events')
    op.drop_index(op.f('ix_distress_events_evaluated_at'), table_name='distress_events')
    op.drop_table('distress_events')
    op.drop_index(op.f('ix_credit_requests_user_id'), table_name='credit_requests')
    op.drop_index(op.f('ix_credit_requests_id'), table_name='credit_requests')
    op.drop_index(op.f('ix_credit_requests_created_at'), table_name='credit_requests')
    op.drop_table('credit_requests')
    op.drop_index(op.f('ix_coach_conversations_user_id'), table_name='coach_conversations')
    op.drop_index(op.f('ix_coach_conversations_id'), table_name='coach_conversations')
    op.drop_index(op.f('ix_coach_conversations_created_at'), table_name='coach_conversations')
    op.drop_table('coach_conversations')
    op.drop_index(op.f('ix_category_saving_policies_id'), table_name='category_saving_policies')
    op.drop_table('category_saving_policies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_provider_events_provider_event_id'), table_name='payment_provider_events')
    op.drop_index(op.f('ix_payment_provider_events_id'), table_name='payment_provider_events')
    op.drop_table('payment_provider_events')
    op.drop_index(op.f('ix_merchants_merchant_code'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_investment_products_id'), table_name='investment_products')
    op.drop_table('investment_products')
    # ### end Alembic commands ###
